# Generated by Django 3.0.6 on 2020-08-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='raspberry',
        ),
    ]
