# Generated by Django 3.0.6 on 2020-08-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clothes_category_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='social',
        ),
        migrations.RemoveField(
            model_name='clothes_category',
            name='pattern',
        ),
        migrations.AddField(
            model_name='account',
            name='platform',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Social_Login',
        ),
    ]
