# Generated by Django 3.0.6 on 2020-08-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200808_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
