# Generated by Django 3.0.6 on 2020-08-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_raspberrypi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberrypi',
            name='user',
        ),
    ]
