# Generated by Django 3.0.6 on 2020-08-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200808_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberrypi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
