# Generated by Django 3.0.6 on 2020-08-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200808_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberrypi',
            name='user',
        ),
        migrations.AlterField(
            model_name='account',
            name='platform',
            field=models.IntegerField(default=0),
        ),
    ]
