# Generated by Django 3.0.6 on 2020-08-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200808_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='platform',
            field=models.IntegerField(default=1),
        ),
    ]
