# Generated by Django 3.0.6 on 2020-08-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20200808_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='platform',
            field=models.IntegerField(default=0),
        ),
    ]
