# Generated by Django 3.0.6 on 2020-08-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200808_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes_category',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
