# Generated by Django 3.0.6 on 2020-08-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200821_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes_category',
            name='category',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
