# Generated by Django 3.0.6 on 2020-09-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200822_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sex',
            field=models.BooleanField(default=True),
        ),
    ]
