# Generated by Django 3.0.6 on 2020-09-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200903_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberrypi',
            name='rasp_id',
        ),
        migrations.RemoveField(
            model_name='raspberrypi',
            name='rasp_password',
        ),
        migrations.AddField(
            model_name='raspberrypi',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
