# Generated by Django 3.0.6 on 2020-09-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200906_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='raspberrypi',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
