# Generated by Django 3.0.6 on 2020-09-09 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_raspberrypi_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raspberrypi',
            name='status',
        ),
    ]
