# Generated by Django 3.0.6 on 2020-09-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_raspberrypi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'None')], max_length=1),
        ),
    ]
