# Generated by Django 3.0.6 on 2020-09-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20200909_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='recommend_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommend_enable',
            field=models.BooleanField(default=False),
        ),
    ]
