# Generated by Django 3.0.6 on 2020-09-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20200918_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommend_enable',
        ),
    ]
