# Generated by Django 3.0.6 on 2020-09-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20200918_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency_fashion',
            name='dress',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='dress',
        ),
    ]
