# Generated by Django 3.0.6 on 2020-09-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20200918_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency_fashion',
            name='neat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fre_neat', to='accounts.Clothes_category'),
        ),
        migrations.AddField(
            model_name='frequency_fashion',
            name='outer2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fre_outer2', to='accounts.Clothes_category'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='neat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_neat', to='accounts.Clothes_category'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='outer2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec_outer2', to='accounts.Clothes_category'),
        ),
    ]
